### ISSUE TITLE
AI Crashing

### ISSUE THREAD

**Issue by SkaceKamen** [open-terraforming/open-terraforming#60]
**Describe the bug**

```
12:11:30.044Z Game(1c..cd) Joana TypeError: Cannot set properties of undefined (setting 'played')
    at Object.perform (/shared/src/cards/effects/mark-card-as-unplayed.ts:16:47)
    at /shared/src/game/scoring/utils.ts:147:8
    at Array.forEach (<anonymous>)
    at evalEffect (/shared/src/game/scoring/utils.ts:146:13)
    at evalEffect (/shared/src/game/scoring/utils.ts:187:12)
    at getBestArgs (/shared/src/game/scoring/utils.ts:209:9)
    at useCardScore (/shared/src/game/scoring/use-card-score.ts:12:20)
    at /shared/src/game/bot.ts:499:34
    at Array.forEach (<anonymous>)
    at Bot.doSomething (/shared/src/game/bot.ts:498:8)
```

**To Reproduce**

Bot has to have a Viron, the issue happens immediately.

**Expected behavior**

Bot shouldn't crash on this

**Comment by SkaceKamen** [comment]
The issue is that there's no card to be re-played and the AI seems to be unable to deal with that.

**Comment by SkaceKamen** [comment]
```
Failed to score robotic_workforce with [ [] ] due to Error: Invalid card index undefined
    at Object.perform (/shared/src/cards/effects.ts:1426:11)
    at /shared/src/game/scoring/utils.ts:147:8
    at Array.forEach (<anonymous>)
    at evalEffect (/shared/src/game/scoring/utils.ts:146:13)
    at evalEffect (/shared/src/game/scoring/utils.ts:187:12)
    at getBestArgs (/shared/src/game/scoring/utils.ts:209:9)
    at playCardScore (/shared/src/game/scoring/play-card-score.ts:9:26)
    at /shared/src/game/bot.ts:449:35
    at Array.forEach (<anonymous>)
    at Bot.doSomething (/shared/src/game/bot.ts:448:8)

12:49:50.418Z Game(1c..cd) Joana Error: Invalid card index undefined
    at Object.perform (/shared/src/cards/effects.ts:1426:11)
    at /shared/src/game/scoring/utils.ts:147:8
    at Array.forEach (<anonymous>)
    at evalEffect (/shared/src/game/scoring/utils.ts:146:13)
    at evalEffect (/shared/src/game/scoring/utils.ts:187:12)
    at getBestArgs (/shared/src/game/scoring/utils.ts:209:9)
    at playCardScore (/shared/src/game/scoring/play-card-score.ts:9:26)
    at /shared/src/game/bot.ts:449:35
    at Array.forEach (<anonymous>)
    at Bot.doSomething (/shared/src/game/bot.ts:448:8)
```

**Comment by SkaceKamen** [comment]
New crash:
```
[server] 20:27:41.858Z Game(d6..aa) Rick Error: Invalid argument supplied, expected amount of type number, got "0"
[server]     at Object.perform (E:\dev\games\open-terraforming\shared\src\cards\effectsGrouped.ts:231:11)
[server]     at E:\dev\games\open-terraforming\shared\src\cards\effectsGrouped.ts:592:7
[server]     at Array.forEach (<anonymous>)
[server]     at Object.perform (E:\dev\games\open-terraforming\shared\src\cards\effectsGrouped.ts:591:12)
[server]     at E:\dev\games\open-terraforming\shared\src\game\scoring\utils.ts:165:8
[server]     at Array.forEach (<anonymous>)
[server]     at evalEffect (E:\dev\games\open-terraforming\shared\src\game\scoring\utils.ts:164:13)
[server]     at E:\dev\games\open-terraforming\shared\src\game\scoring\utils.ts:199:12
[server]     at Array.map (<anonymous>)
[server]     at evalEffect (E:\dev\games\open-terraforming\shared\src\game\scoring\utils.ts:196:32)
```

Caused by `resourceChangeByArg`
